### PR TITLE
All references to ::hydrate changed to ::hr

### LINKED ISSUE #173: Remove references to ::hydrate in favor of ::hr
## Feature Reasoning

The original `::hydrate` command is quite lengthy to type out and is generally not recommended over the `::hr` alias which is much easier to type. 

## Feature Description

The goal of this enhancement is to allow the `::hydrate` command to remain functional for legacy purposes, but remove it from any user-facing documentation in favor of `::hr`.

There are three parts to this enhancement:

1. Replace all references of `::hydrate` with `::hr` in the README
2. Replace all references of `::hydrate` with `::hr` in the welcome messages
    - See `HYDRATE_WELCOME_TEXT_LIST` in `HydrateReminderPlugin.java`
3. Remove the reference to `::hydrate` within the help command message
    - See `handleHydrateHelpCommand()` in `HydrateReminderPlugin.java`

Making these changes should still allow the `::hydrate` command to work but remove it from all messages and documentation.

## Additional Context

It is possible that there are more references to `::hydrate` that I have missed. If any more references are found, it would be good to remove/replace them as well.

### PR DESCRIPTION
**Pull request by Krishpandya682**
## Associated Issue

Closes #173 

## Implemented Solution

I have replaced all the references to ::hydrate in favor of ::hr
## Testing Details

Operating System: 
RuneLite Version:

### CODE REVIEW

**Review by jmakhack — CHANGES_REQUESTED** [review]
Looks like part 1 and 2 mentioned in the issue are resolved here, but part 3 is not fixed with these changes.

The output of running the help command is the following:
image

The help message needs to be updated. See `handleHydrateHelpCommand()`.

**Comment by Krishpandya682** [comment]
Hi, sorry I am a little confused, do you want the "Available commands: ::hydrate or ::hr ..." to just say "Available commands: :::hr ..."

**Comment by jmakhack** [comment]
@Krishpandya682, that is correct. The mention of `::hydrate` should be removed and the remaining message should just be `Available commands: ::hr next, ...`

**Comment by jmakhack** [comment]
@all-contributors please add @Krishpandya682 for code and documentation

**Review by jmakhack — APPROVED** [review]
Thanks for making the update to the pull request! Looks good so I'm approving and merging it.

**Pull request merged**
