### PR TITLE
Changes time next/prev string to only display segments as needed

### LINKED ISSUE #66: Text for next and prev commands should not display hours and/or minutes when not needed
## Bug Description

Instead of showing `0 hours...`, only show minutes and seconds for `::hydrate next` and `::hydrate prev` commands. Also instead of showing `0 hours 0 minutes...`, only show seconds for the commands. Basically, only show the time units that are needed. When the larger time units are 0, remove all that are unnecessary.

## Steps to Reproduce

1. Set the hydrate reminder interval to a value less than 60 minutes
2. Type in `::hydrate next` into the chatbox
3. Observe that the resulting message will always unnecessarily begin with `0 hours`

## Expected Behavior

Only the time units that need to be shown should be shown. For example `0 hours 0 minutes 30 seconds` should be replaced with just `30 seconds`. However, do note that `1 hour 0 minutes 10 seconds` is okay and minutes should not be removed in this case because a higher order time unit is non-zero (`1 hour`).

## Screenshots

hydrate_commands

## Environment

Operating System: macOS Big Sur
RuneLite Version: 1.7.15

### PR DESCRIPTION
**Pull request by neilrush**
## Associated Issue

Closes #66

## Implemented Solution

solved by using a string builder to append the segments as needed
## Testing Details

Tested by inputting several different values into the time interval config field
Operating System: Windows 10 pro 20H2
RuneLite Version:  1.7.15

## Screenshots

image

### CODE REVIEW

**Review by jmakhack — COMMENTED** [review]
The changes look good to me.
Can you update the timeDisplay unit test in `hydrateReminderPluginTest` to test these changes?

**Comment by neilrush** [comment]
The test is now updated

**Review by jmakhack — APPROVED** [review]
Approved your changes and going to merge them in.
Thanks for your contributions!

**Comment by jmakhack** [comment]
@all-contributors please add @neilrush for code and tests

**Pull request merged**
