### PR TITLE
Add hype personality

### LINKED ISSUE #192: Add new hydrate message personality type: Hype
## Feature Reasoning

With the introduction of personality types for hydration break messages, it would be nice to add more new personality types. One such personality type to add is: `hype`.

## Feature Description

The purpose of this feature request is to add a new personality type `hype` to the currently existing personality types available for the hydrate break messages. The new personality type should be made selectable via the personality type dropdown menu in the hydrate reminder configuration menu.

To start off, adding at least 12 new messages should be good and more can be added later.
An example of a hype message could be something like: `Hydration break time! Let's gooooooooooo`

## Possible Alternatives

If not really hype, any messages that could be considered energetic or excited can be considered OK for this personality type.

## Additional Context

To complete this work, the following two files need to be edited:
- [HydrateReminderPersonalityType.java](https://github.com/jmakhack/hydrate-reminder/blob/master/src/main/java/com/hydratereminder/HydrateReminderPersonalityType.java)
- [HydrateBreakMessageDictionary.java](https://github.com/jmakhack/hydrate-reminder/blob/master/src/main/java/com/hydratereminder/dictionary/HydrateBreakMessageDictionary.java)

Looking into these two files should give a clear indication on how to implement this feature, but please do ask any questions in the comments below if needed. Please also add and/or update unit tests where necessary.

Please refer to [CONTRIBUTING.md](https://github.com/jmakhack/hydrate-reminder/blob/master/CONTRIBUTING.md) for info on how to setup, build, run, and test this project. Feel free to ping @jmakhack in the comments below with any questions if needed. Also, join the [Discord](https://discord.gg/RTgxfFW9mS) to meet and engage with other contributors!

[](https://discord.gg/RTgxfFW9mS)

### PR DESCRIPTION
**Pull request by Prajwalrayal**
## Associated Issue

Closes #192 

## Implemented Solution

Added a new personality type through Arraylist and created an extra case for the switch

## Testing Details

Operating System: 
RuneLite Version:

### CODE REVIEW

**Review by jmakhack — CHANGES_REQUESTED** [review]
Hi @Prajwalrayal, your changes look good.

Can you just also update the unit test in [HydrateBreakMessageDictionaryTest.java](https://github.com/jmakhack/hydrate-reminder/blob/master/src/test/java/com/hydratereminder/dictionary/HydrateBreakMessageDictionaryTest.java) to include this new personality type?

**Comment by Prajwalrayal** [comment]
Sure, Updated!

**Comment by jmakhack** [comment]
@all-contributors please add @Prajwalrayal for code and tests

**Review by jmakhack — APPROVED** [review]
Everything looks good now @Prajwalrayal.

Thanks for the contribution! :)

**Pull request merged**
