### PR TITLE
Add new hydrate message personality type: Motivational

### LINKED ISSUE #191: Add new hydrate message personality type: Motivational
## Feature Reasoning

With the introduction of personality types for hydration break messages, it would be nice to add more new personality types. One such personality type to add is: `motivational`.

## Feature Description

The purpose of this feature request is to add a new personality type `motivational` to the currently existing personality types available for the hydrate break messages. The new personality type should be made selectable via the personality type dropdown menu in the hydrate reminder configuration menu.

To start off, adding at least 12 new messages should be good and more can be added later.
An example of an motivational message could be something like: `It's time to rejuvinate and refresh the body with water for a better and healthier you`

## Possible Alternatives

If not really motivational, any messages that could be considered inspirational and/or encouraging can be considered OK for this personality type.

## Additional Context

To complete this work, the following two files need to be edited:
- [HydrateReminderPersonalityType.java](https://github.com/jmakhack/hydrate-reminder/blob/master/src/main/java/com/hydratereminder/HydrateReminderPersonalityType.java)
- [HydrateBreakMessageDictionary.java](https://github.com/jmakhack/hydrate-reminder/blob/master/src/main/java/com/hydratereminder/dictionary/HydrateBreakMessageDictionary.java)

Looking into these two files should give a clear indication on how to implement this feature, but please do ask any questions in the comments below if needed. Please also add and/or update unit tests where necessary.

Please refer to [CONTRIBUTING.md](https://github.com/jmakhack/hydrate-reminder/blob/master/CONTRIBUTING.md) for info on how to setup, build, run, and test this project. Feel free to ping @jmakhack in the comments below with any questions if needed. Also, join the [Discord](https://discord.gg/RTgxfFW9mS) to meet and engage with other contributors!

[](https://discord.gg/RTgxfFW9mS)

### PR DESCRIPTION
**Pull request by aakash232**
## Associated Issue

Closes #191 

## Implemented Solution

Added the MOTIVATIONAL personality inside [HydrateReminderPersonalityType.java](https://github.com/jmakhack/hydrate-reminder/blob/master/src/main/java/com/hydratereminder/HydrateReminderPersonalityType.java).
Added the MOTIVATIONAL dictionary into a separate function and then added the option to the switch case inside [HydrateBreakMessageDictionary.java](https://github.com/jmakhack/hydrate-reminder/blob/master/src/main/java/com/hydratereminder/dictionary/HydrateBreakMessageDictionary.java)

## Testing Details

No testing has been done, as the change only adds a new option for the hydration message sent to users. No new functionality was added nor a change in the project functionality was done.
(However, testing will be done if required.)

### CODE REVIEW

**Review by mslowiak — APPROVED** [review]

**Comment by aakash232** [comment]
@jmakhack is the PR good for merge?

**Comment by jmakhack** [comment]
> @jmakhack is the PR good for merge?

@aakash232 I'm going through and merging approved pull requests in the order that they have been opened. As such, there appear to be merge conflicts now. Can you resolve the conflicts? I will merge yours afterwards.

**Comment by aakash232** [comment]
> > @jmakhack is the PR good for merge?
> 
> @aakash232 I'm going through and merging approved pull requests in the order that they have been opened. As such, there appear to be merge conflicts now. Can you resolve the conflicts? I will merge yours afterwards.

@jmakhack Sure. Pls go as per the flow. If the conflicts still continue, do let me know. I'll make a new PR after you merge existing ones. The merge will be safe then. But If its solved now then now issues!

**Comment by mslowiak** [comment]
> f the conflicts still continu

You don't need to make a new PR.
When you merge with master / rebase on master then you can force push on your actual branch :)

**Review by jmakhack — APPROVED** [review]

**Pull request merged**
