### PR TITLE
SOLVED :Fix bean members should serialize issues #293

### PR DESCRIPTION
**Pull request by manish-singh-bisht**
Solved issue #293 Fix bean members should serialize issues #293

### CODE REVIEW

**Comment by manish-singh-bisht** [comment]
I by mistake deleted one of the files but i restored it , so no worries. 
Please review it, if any issues I will solve them.
Thank you

**Comment by manish-singh-bisht** [comment]
Please review it.

**Comment by manish-singh-bisht** [comment]
All changes done, please review it.

**Review by jmakhack — APPROVED** [review]
The changes look good to me and I've confirmed all 75 instances of the issue are fixed.

Thanks for the contribution! :)

**Pull request merged**
