### PR TITLE
update all-contributorsrc to show 7 contributors per line

### LINKED ISSUE #371: [First Timers Only] Update contributors display to show 7 contributors per line
## Task Context

Given the increasing amount of contributors on this project, it would be nice to condense down the display of contributors in the README.

## Acceptance Criteria / Goals

Update [.all-contributorsrc](https://github.com/jmakhack/hydrate-reminder/blob/master/.all-contributorsrc) so that the @all-contributors bot will update the number of contributors per line the next time it is run.

## Additional Notes

Please refer to [CONTRIBUTING.md](https://github.com/jmakhack/hydrate-reminder/blob/master/CONTRIBUTING.md) for info on how to setup, build, run, and test this project. Feel free to ping @jmakhack in the comments below with any questions if needed. Also, join the [Discord](https://discord.gg/RTgxfFW9mS) to meet and engage with other contributors!

[](https://discord.gg/RTgxfFW9mS)

### PR DESCRIPTION
**Pull request by MrinaliniU**
## Associated Issue

Closes #371

## Implemented Solution

Updated the contributorsPerLine to `7` from `5`.

## Testing Details

Operating System: NA
RuneLite Version: NA

### CODE REVIEW

**Comment by MrinaliniU** [comment]
@jmakhack Hello :) if you think this PR looks good do you think you can merge this? thank you!

**Comment by jmakhack** [comment]
Looks good. I was just checking with the current assignee to see if they were still working on this.

Can you leave a comment in #371 so I can assign it to you?

**Comment by MrinaliniU** [comment]
> hydrate

Thank you! I have added a comment in the issue requesting you to assign the issue #371 to me.

**Comment by MrinaliniU** [comment]
> Looks good. I was just checking with the current assignee to see if they were still working on this.
> 
> Can you leave a comment in #371 so I can assign it to you?
@jmakhack Thank you! I have added a comment in the issue requesting you to assign the issue https://github.com/jmakhack/hydrate-reminder/issues/371 to me.

**Comment by jmakhack** [comment]
@all-contributors please add @MrinaliniU for docs

**Review by jmakhack — APPROVED** [review]

**Pull request merged**
