### PR TITLE
Add hydrate animation

### LINKED ISSUE #146: Perform a hydration animation whenever a hydration break is occurring
## Feature Reasoning

It would be fun to have an animation played whenever it is time to take a hydration break and also whenever the `hydrate` chat command is used.

## Feature Description

There should be two things done as part of the implementation work for this feature request:
1. Add a new configuration option for enabling/disabling this `Hydrate animation` setting
    - See `com/hydratereminder/HydrateReminderConfig.java`
2. Play the `AnimationID.CONSUMING` animation whenever the `incrementCurrentSessionHydrationBreaks` is called in `com/hydratereminder/HydrateReminderPlugin.java`
    - See `net/runelite/api/AnimationID.java` and https://static.runelite.net/api/runelite-api/net/runelite/api/Actor.html#setAnimation(int)

## Possible Alternatives

There are likely other animations that can be used here and may be better than the `CONSUMING` animation. A separate feature enhancement will be opened to address this by either using the best animation found for hydration or by allowing the user to select from a list of animations.

## Additional Context

Add unit tests where necessary/applicable. Feel free to ask any questions in the comments below.

### PR DESCRIPTION
**Pull request by mslowiak**
## Associated Issue

Closes #146

## Implemented Solution

Adding hydrate animation when hydrating.

## Testing Details

I have added unit tests that are covering that functionality.

### CODE REVIEW

**Comment by mslowiak** [comment]
@jmakhack Please take a look on that

**Comment by jmakhack** [comment]
@all-contributors please add @mslowiak for code and tests

**Comment by mslowiak** [comment]
@jmakhack
What is your idea to proceed with that PR? Since it is 2.0.0 will you merge it to the master and after some time release the 2.0.0 version? Other tasks can be dependent with other that are included to 2.0.0

**Review by jmakhack — APPROVED** [review]
The code and tests look good to me! I tested the build and it works as expected.
Thanks for the contribution!

**Pull request merged**
