### PR TITLE
fix: rename variables as per Codacy review

### LINKED ISSUE #333: [First Timers Only] Fix field naming conventions issues
## Task Context

The Codacy Static Code Analysis system is reporting field naming conventions issue(s). The reported issue(s) can be found at:

https://app.codacy.com/gh/jmakhack/hydrate-reminder/issues?bid=22863237&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6WyJKYXZhIl19LHsiaWQiOiJDYXRlZ29yeSIsInZhbHVlcyI6WyJDb2RlU3R5bGUiXX0seyJpZCI6IkxldmVsIiwidmFsdWVzIjpbXX0seyJpZCI6IlBhdHRlcm4iLCJ2YWx1ZXMiOlsiODA4MyJdfSx7ImlkIjoiQXV0aG9yIiwidmFsdWVzIjpbXX1d

## Acceptance Criteria / Goals

The goal of this task is to fix the issue(s) reported by Codacy.

## Additional Notes

After opening a pull request, the Codacy Static Code Analysis will automatically run. It should report that the fixed issue(s) if this task is completed successfully.

Please refer to [CONTRIBUTING.md](https://github.com/jmakhack/hydrate-reminder/blob/master/CONTRIBUTING.md) for info on how to setup, build, run, and test this project. Feel free to ping @jmakhack in the comments below with any questions if needed. Also, join the [Discord](https://discord.gg/RTgxfFW9mS) to meet and engage with other contributors!

[](https://discord.gg/RTgxfFW9mS)

### PR DESCRIPTION
**Pull request by A-5ingh**
## Associated Issue

Closes #333 

## Implemented Solution

Corrected the variable names and occurrences as per Pascal casing.

## Testing Details

Operating System: MacOS 12.6
RuneLite Version: 1.1.1

### CODE REVIEW

**Review by jmakhack — APPROVED** [review]
@A-5ingh, the changes look good and I've verified they are reported as fixed on Codacy.

Thanks for the contribution! :)

**Comment by jmakhack** [comment]
@all-contributors please add @A-5ingh for code

**Comment by A-5ingh** [comment]
> @A-5ingh, the changes look good and I've verified they are reported as fixed on Codacy.
> 
> Thanks for the contribution! :)

No worries! If there are other issues which are not taken up by anyone I can contribute there as well.

**Comment by jmakhack** [comment]
> > @A-5ingh, the changes look good and I've verified they are reported as fixed on Codacy.
> > Thanks for the contribution! :)
> 
> No worries! If there are other issues which are not taken up by anyone I can contribute there as well.

@A-5ingh now that hacktoberfest is slowing down with less contributors signing up for issues, you can take #332 as well if you'd like :)

**Comment by A-5ingh** [comment]
> > > @A-5ingh, the changes look good and I've verified they are reported as fixed on Codacy.
> > > Thanks for the contribution! :)
> > 
> > 
> > No worries! If there are other issues which are not taken up by anyone I can contribute there as well.
> 
> @A-5ingh now that hacktoberfest is slowing down with less contributors signing up for issues, you can take #332 as well if you'd like :)

Sure, please assign #332 to me as well.

**Comment by A-5ingh** [comment]
@jmakhack can you please add the label `hacktoberfest-accepted` to this MR.

**Pull request merged**
