### PR TITLE
Issue 99: Prepare commands and handlers for future refactoring

### LINKED ISSUE #99: Project structure refactoring
## Task Context
Despite hydrate-reminder being a relatively small project, it's main logic within `HydrateReminderPlugin.java` is well over 600 lines of code in length. As new enhancements are continually being planned for this project, this one class containing all the main logic can easily get out of hand and hard to maintain as time goes on.

As a result, I think this is a good point to start doing some overall refactoring on this project. The logic within `HydrateReminderPlugin.java` should be split out into separate classes in a way that makes logical sense.

For example, all the logic for handling chat commands could be separated out to a `HydrateReminderCommandHandler.java` class. The logic for each command can also be split into separate classes but some thought should be done as to not "over-engineer" the project into a big complicated mess. It's important to keep in mind that **the goal of this refactoring is to create a healthy codebase for easier maintenance and development** as opposed to making things more complicated and difficult.

As I am not primarily a Java developer by trade, any input on project structure and design for this project is greatly appreciated. Looking into how other official and third-party plugins structure their project may provide some good insight as well.

Join the [Discord](https://discord.gg/RTgxfFW9mS) to meet and engage with other contributors!

[](https://discord.gg/RTgxfFW9mS)

### PR DESCRIPTION
**Pull request by mslowiak**
## Associated Issue
Closes #99 

## Implemented Solution
Prepared a skeleton for dividing command into separate classes.
We need to create follow-up issues to allow contributors to work on that refactoring.

Things that needs to be done (issues to be created):
- Extract message sender logic to separate class
- Extract `help` command logic to `HelpCommandHandler`
- Extract `hydrate` command logic to `HydrateCommandHandler`
- Extract `next` command logic to `NextCommandHandler`
- Extract `prev` command logic to `PrevCommandHandler`
- Extract `reset` command logic to `ResetCommandHandler`
- Extract `total` command logic to `TotalCommandHandler`

### CODE REVIEW

**Comment by jmakhack** [comment]
Hey @mslowiak. At a quick glance, this looks great! I'll review this as soon as I get the chance.

**Comment by mslowiak** [comment]
@jmakhack friendly reminder 😉

**Comment by jmakhack** [comment]
Hi @mslowiak, thanks for doing all this work. Sorry for the long delay in getting this review done but it all looks good!

The codacy static code analysis is showing up as failing but I'll bypass it for this pull request since you're essentially adding boilerplate code that can be used to open a bunch of new issues for people to work on.

**Comment by mslowiak** [comment]
@jmakhack Will you be able to create those issues that I listed in description or you want me to do that?

**Comment by jmakhack** [comment]
@mslowiak If you're able to at least create basic issues for the new classes, that would be very much appreciated! I can fill in any additional details afterwards.

**Comment by mslowiak** [comment]
@jmakhack Great, I will do that today

**Comment by mslowiak** [comment]
@jmakhack 
I created the tasks that I mentioned in the PR with relevant description. Would be great if you can take a look at them and apply proper labels ;)

BTW. What do you think about creating a discord server for this project? It will be easier to talk with people that are contributing here. Secondly, hacktoberfest is close... :)

**Pull request merged**
