### PR TITLE
Added additional strings to the hydrate reminder messages

### LINKED ISSUE #86: Add more unique hydrate reminder messages to cycle through
## Feature Reasoning

There can always be more hydrate reminder messages to cycle through.\
The current list of 12 starts to repeat itself not after long.

## Feature Description

Add a variety of new hydrate reminder messages for the plugin to cycle through.\
The goal for the v.1.2.0 release is to have at least 30 unique hydrate reminder messages.

## Additional Context

Current set of hydrate reminder messages:
hydrate_messages

### PR DESCRIPTION
**Pull request by paulritzman**
## Associated Issue

Closes #86

## Implemented Solution

Added 18 strings to the ArrayList of hyrate reminder messages to meet the v1.2.0 goal of 30 total reminder messages.

## Testing Details

Ran the unit tests defined in HydrateReminderChatMessageTypeTest and HydrateReminderPluginTest, both passing.

Attempted to run HydrateReminderTest, which successfully launched the game, but was unable to install the plugin and receive hydration reminders.

Operating System: Windows 10
RuneLite Version: 1.7.18

### CODE REVIEW

**Comment by jmakhack** [comment]
@paulritzman, thanks for the contribution! I'll test this sometime soon and approve this pull request once I confirm it's working as expected.

If you're having issues testing your changes in the game, try setting the `runeLiteVersion` in `build.gradle` to the latest RuneLite version indicated on runelite.net (1.7.18 as of writing this). The plugin with the latest code should then be automatically installed when you run `HydrateReminderTest`.

**Comment by paulritzman** [comment]
@jmakhack Thank you for the advice! That did the trick, and the new reminder messages were appearing! Just for transparency, in case any contributors come across this same scenario, I also had to remove the previously installed version of the plugin before running <code>HydrateReminderTest</code>. It ran as expected with the previous version installed, but now there were two plugins, causing double the reminder messages to appear.

Also, I will be updating these reminders and making a new push shortly, as I noticed the punctuation is incorrect. Each reminder ends in ", [player name]." But some of the new reminders already have punctuation at the end.

**Comment by paulritzman** [comment]
hydrate_reminder

**Review by jmakhack — APPROVED** [review]

**Comment by jmakhack** [comment]
Looks good to me! Approved and merging it in shortly.
And thanks for the debugging notes. Testing is a little bit tricky at times with the constantly changing client versions.

**Comment by jmakhack** [comment]
@all-contributors please add @paulritzman for code

**Pull request merged**
